### ISSUE TITLE
Add support for loading all env

### ISSUE THREAD

**Issue by rootux** [morficus/cypress-dotenv#1]
Instead of loading only CYPRES_ env variable - Add support to load all env variables defined in the .env file

**Comment by morficus** [comment]
🤔 not a bad idea.
the ability to load all vs only prefixed env vars could be controlled by an option. 

I'll try to get to this this week. otherwise PRs are welcomed 🙏

**Comment by morficus** [comment]
PR #5  will address this 🎉
