### ISSUE TITLE
TypeError: config is not a function

### ISSUE THREAD

**Issue by pixelass** [morficus/cypress-dotenv#16]
<img width="976" alt="cypress" src="https://user-images.githubusercontent.com/1148334/98661322-9803c980-2346-11eb-8d9a-653908898fd5.png">

`cypress/plugins/index.js`

```js
const dotenvPlugin = require("cypress-dotenv");
module.exports = (on, config) => {
	config = dotenvPlugin(config);
	return config;
};
```

versions: 

```
"cypress": "^5.5.0",
"cypress-dotenv": "^1.2.2",
"dotenv": "^8.2.0",
```

**Comment by m4x3d** [comment]
I know its a bit late, but possibly it helps another person. Just use an ES6 import instead of require, like this:

import dotenvPlugin from 'cypress-dotenv';

**Comment by pixelass** [comment]
also:

```js
const {default: dotenvPlugin} = require("cypress-dotenv");
```
