### ISSUE TITLE
Dotenv option debug=false shows debug error

### ISSUE THREAD

**Issue by coding-frank** [morficus/cypress-dotenv#26]
`debug=false`

I have comments in my env file #comment here...

Allthough set to false it throws these debug errors:
**[dotenv][DEBUG] did not match key and value when parsing line 5:** 

```
config = dotenvPlugin(
  config,
    {
	debug: false,
	path: path.join(__dirname, "../../.env.development"),
    },
    true
);
```

**Comment by morficus** [comment]
hey @coding-frank -- I know this is 3 years later... but are you still running into this issue? I'm not able to replicate it.
If you are, could you share a branch that produces the issue please?

**Comment by morficus** [comment]
I'm going to close this issue for now, but please feel free to reopen it if you're still having a problem
