### ISSUE TITLE
cypress-dotenv not working

### ISSUE THREAD

**Issue by RAMKI14** [morficus/cypress-dotenv#35]
Hi,

I have installed cypress-dotenv and followed the instructions, still not working.
Implementing this in cypress, cucumber-bdd, with the page object model.

**Added below code in the cypress.config.js**
`const dotenvPlugin = require("cypress-dotenv");
module.exports = (on, config) => {
  config = dotenvPlugin(config);
  return config;
};`

**Calling it in the test**:
`cy.log(Cypress.env("CYPRESS_HELLO"));`

**But it is printing as below in the log-in test runner:**
log

**Comment by nicojones** [comment]
Probably because it's developed for Cypress<10

**Comment by morficus** [comment]
@RAMKI14 check out the updated README, it now has information on how to set it up to work with Cypress v10
